---
title: Financement des entreprises et des particuliers
author: Lisa Perherin
date: Septembre 2024
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

## LE FINANCEMENT DES ENTREPRISES

```{r setup, include=FALSE}
# Chargement des bibliothèques nécessaires
library(dplyr)
library(ggplot2)
library(insee)
library(zoo)

data <- get_insee_idbank("001656101", startPeriod = "1991-01") %>%
  add_insee_metadata()

moyenne_2010_2019 <- data %>%
  filter(DATE >= as.Date("2010-01-01") & DATE <= as.Date("2019-12-31")) %>%
  summarise(moyenne = mean(OBS_VALUE, na.rm = TRUE)) %>%
  pull(moyenne)
```

```{r graphique, echo=FALSE, fig.show='hold',warning=FALSE,fig.align='center',fig.width=8, fig.height=5}
ggplot(data, aes(x = DATE, y = OBS_VALUE)) +
  geom_line(color = "#2c3e50", size = 1.2) + 
  ggtitle("Nombre de défaillances d'entreprises", 
          subtitle = "Cumul brut glissant sur 12 mois - France - Tous secteurs d'activité") +
  labs(caption = sprintf("Dernière màj : %s - Source Insee", data$TIME_PERIOD[1])) +
  geom_hline(yintercept = moyenne_2010_2019, linetype = "dashed", color = "cyan3", size = 1) +
  annotate("text", x = as.Date("2015-01-01"), y = moyenne_2010_2019 - 5000, 
           label = sprintf("Moyenne 2010-2019: %.0f", moyenne_2010_2019), 
           color = "cyan3", size = 4, fontface = "bold", vjust = -1) +
  scale_x_date(date_labels = "%Y", date_breaks = "2 years") +
  labs(x = "Année", y = "Nombre de défaillances") +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5, color = "#34495e"),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "#7f8c8d"),
    axis.title.x = element_text(size = 12, color = "#2c3e50"),
    axis.title.y = element_text(size = 12, color = "#2c3e50"),
    axis.text = element_text(size = 10, color = "#34495e"),
    panel.grid.major = element_line(color = "gray85", size = 0.5),
    panel.grid.minor = element_line(color = "gray95", size = 0.25)
  )

```












```{r setupp, include=FALSE}
library(scales)

data1 <- get_insee_idbank("010756084", startPeriod = "2000-01") %>%
  add_insee_metadata()

data2 <- get_insee_idbank("001564319", startPeriod = "2000-01", endPeriod ="2011-10-01") %>%
  add_insee_metadata()

# Combiner les données de data
data_combined <- bind_rows(data1, data2)

# Charger les données pour data2
data3 <- get_insee_idbank("001787502", startPeriod = "2000-01",endPeriod ="2011-10-01") %>%
  add_insee_metadata()

data4 <- get_insee_idbank("010756114", startPeriod = "2000-01") %>%
  add_insee_metadata()

# Combiner les données de data2
data2_combined <- bind_rows(data3, data4)


# Trier data_combined par DATE
data_combined <- data_combined %>%
  arrange(DATE)

# Trier data2_combined par DATE
data2_combined <- data2_combined %>%
  arrange(DATE)

combined_data <- left_join(data_combined, data2_combined, by = "DATE") %>%
  mutate(SUM_4_TRIMESTRES_DATA = rollsum(OBS_VALUE.x, k = 4, fill = NA, align = "right"),
         SUM_4_TRIMESTRES_DATA2 = rollsum(OBS_VALUE.y, k = 4, fill = NA, align = "right")) %>%
  select( DATE,OBS_VALUE.x, SUM_4_TRIMESTRES_DATA,OBS_VALUE.y, SUM_4_TRIMESTRES_DATA2)
```

```{r graphiquee, echo=FALSE, fig.show='hold',warning=FALSE,fig.align='center',fig.width=8, fig.height=5}

# Création du graphique
ggplot(combined_data, aes(x = DATE)) +
  geom_line(aes(y = SUM_4_TRIMESTRES_DATA, color = "Data"), size = 1.2) + 
  geom_line(aes(y = SUM_4_TRIMESTRES_DATA2, color = "SUM_4_TRIMESTRES_DATA2"), size = 1.2) + 
  ggtitle("Nombre de créations d'entreprises - France", 
          subtitle = "Cumul glissant sur 4 trimestres") +
  labs(caption = sprintf("Dernière màj : %s - Source Insee", max(combined_data$DATE))) +
  scale_x_date(date_labels = "%Y", date_breaks = "2 years") +

  labs(x = "Année", y = "Nombre de créations d'entreprises") +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5, color = "#34495e"),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "#7f8c8d"),
    axis.title.x = element_text(size = 12, color = "#2c3e50"),
    axis.title.y = element_text(size = 12, color = "#2c3e50"),
    axis.text = element_text(size = 10, color = "#34495e"),
    panel.grid.major = element_line(color = "gray85", size = 0.5),
    panel.grid.minor = element_line(color = "gray95", size = 0.25),
    legend.position = "bottom"  # Placer la légende en bas

  ) +
    scale_y_continuous(labels = scales::comma) +  # Formater les valeurs de l'axe Y sans notation scientifique

  scale_color_manual(name = "Séries",
                     values = c("Data" = "#2c3e50", "SUM_4_TRIMESTRES_DATA2" = "cyan3"),
                     labels = c("Y compris micro-entreprises", "Hors micro-entreprises"))


```
























```{r setuppp, include=FALSE}

data =
  get_insee_idbank("001586998", startPeriod = "2014-01") %>%
  add_insee_metadata()

data2 =
  get_insee_idbank("001586997", startPeriod = "2014-01") %>%
  add_insee_metadata()

data3 =
  get_insee_idbank("001586934", startPeriod = "2014-01") %>%
  add_insee_metadata()

data_combined <- bind_rows(
  data %>% mutate(Series = "Second oeuvre"),
  data2 %>% mutate(Series = "Gros oeuvre"),
  data3 %>% mutate(Series = "Total")
)

```


```{r graphiqueee, echo=FALSE, fig.show='hold',warning=FALSE,fig.align='center',fig.width=8, fig.height=5}

# Création du graphique avec les trois datasets
ggplot(data_combined, aes(x = DATE, y = OBS_VALUE, color = Series)) +
  # Tracer les lignes pour chaque série
  geom_line(size = 1.2) + 
  
  # Titre et sous-titre du graphique
  ggtitle("Enquête mensuelle de conjoncture dans l'industrie du bâtiment", 
          subtitle = "Jugement sur le niveau du carnet de commande - Série brute") +
  
  # Mise à jour de la dernière période (pour data1 ici, vous pouvez choisir celle qui est pertinente)
  labs(caption = sprintf("Dernière màj : %s - Source Insee", data$TIME_PERIOD[1])) +
  
  # Personnalisation des axes
  scale_x_date(date_labels = "%Y", date_breaks = "2 years") +
  labs(x = "Année", y = "Soldes d'opinion", color = "Séries") +
  
  # Définir des couleurs manuellement pour chaque série
  scale_color_manual(values = c("Second oeuvre" = "#2c3e50",  # Rouge pour "Second oeuvre"
                                "Gros oeuvre" = "cyan3",    # Bleu pour "Gros oeuvre"
                                "Total" =  "#3498db")) +       # Vert pour "Total"
  
  # Thème minimal pour un visuel plus épuré
  theme_minimal(base_size = 12) +
  theme(
    # Ajustement des titres et sous-titres
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5, color = "#34495e"),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "#7f8c8d"),
    # Ajustement des axes
    axis.title.x = element_text(size = 12, color = "#2c3e50"),
    axis.title.y = element_text(size = 12, color = "#2c3e50"),
    axis.text = element_text(size = 10, color = "#34495e"),
    # Ajout de lignes de grille légères pour améliorer la lisibilité
    panel.grid.major = element_line(color = "gray85", size = 0.5),
    panel.grid.minor = element_line(color = "gray95", size = 0.25),
        legend.position = "bottom"  # Placer la légende en bas

  )
```

```{r setupppp, include=FALSE}

# carnet de commande dans l'industrie 
# 001585941 

data =
  get_insee_idbank("001585941", startPeriod = "2014-01") %>%
  add_insee_metadata()
```

```{r graphiqueeeee, echo=FALSE, fig.show='hold',warning=FALSE,fig.align='center',fig.width=8, fig.height=5}

ggplot(data, aes(x = DATE, y = OBS_VALUE)) +
  # Tracer la ligne pour la série unique
  geom_line(size = 1.2, color = "#2c3e50") + 
  
  # Titre et sous-titre du graphique
  ggtitle("Enquête mensuelle de conjoncture dans l'industrie manufacturière", 
          subtitle = "Jugement sur le niveau du carnet de commande - Série brute") +
  
  # Mise à jour de la dernière période (automatique en utilisant la première entrée de TIME_PERIOD)
  labs(caption = sprintf("Dernière màj : %s - Source Insee", data$TIME_PERIOD[1])) +
  
  # Personnalisation des axes
  scale_x_date(date_labels = "%Y", date_breaks = "2 years") +
  labs(x = "Année", y = "Soldes d'opinion") +
  
  # Thème minimal pour un visuel plus épuré
  theme_minimal(base_size = 12) +
  theme(
    # Ajustement des titres et sous-titres
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5, color = "#34495e"),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "#7f8c8d"),
    # Ajustement des axes
    axis.title.x = element_text(size = 12, color = "#2c3e50"),
    axis.title.y = element_text(size = 12, color = "#2c3e50"),
    axis.text = element_text(size = 10, color = "#34495e"),
    # Ajout de lignes de grille légères pour améliorer la lisibilité
    panel.grid.major = element_line(color = "gray85", size = 0.5),
    panel.grid.minor = element_line(color = "gray95", size = 0.25)
  )

```
















```{r setupppppp, include=FALSE}

library(scales) 


df_serie <- readRDS("df_serie.rds")

# Filtrer les données depuis 2018
df_filtered <- df_serie %>%
  filter(time_period_end >= as.Date("2018-01-01"))

```

```{r graphiqueeeeee, echo=FALSE, fig.show='hold',warning=FALSE,fig.align='center',fig.width=8, fig.height=5}

# Créer l'histogramme
ggplot(df_filtered, aes(x = time_period_end, y = obs_value)) +
  geom_bar(stat = "identity", fill = "#2c3e50", color = "white") + 
  ggtitle("Total des crédits mobilisés aux PME (y compris les TPE) - France", 
          subtitle = "En milliards d’euros") +
  labs(caption = sprintf("Dernière màj : %s - Source Banque de France", max(df_filtered$time_period_end))) +
  labs(x = "Année", y = "Total des crédits mobilisés (en milliards d'euros)") +
  scale_y_continuous(labels = label_number(scale = 1e-3)) +  # Formatage en milliards
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0.5, color = "#34495e"),
    plot.subtitle = element_text(size = 12, hjust = 0.5, color = "#7f8c8d"),
    axis.title.x = element_text(size = 12, color = "#2c3e50"),
    axis.title.y = element_text(size = 12, color = "#2c3e50"),
    axis.text = element_text(size = 10, color = "#34495e"),
    panel.grid.major = element_line(color = "gray85", size = 0.5),
    panel.grid.minor = element_line(color = "gray95", size = 0.25)
  )
```